# Generated by Django 5.1.15 on 2026-04-22 21:19

import works.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workfile",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=works.models.work_file_upload_to
            ),
        ),
    ]
